name: octtofitterpy backend update
on:
  schedule:
    - cron: '00 00 * * *'
  workflow_dispatch:
jobs:
  update_compat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: pip

      - name: "Install octtofitterpy"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python setup.py install
          # Not needed:
          # python -c 'import octofitterpy; octofitterpy.install()'

      - name: "Get Octofitter.jl latest version"
        id: get-latest
        run: |
          cd $(mktemp -d)
          git clone https://github.com/sefffal/Octofitter.jl
          cd Octofitter.jl
          echo "version=$(git describe --tags --abbrev=0 | sed 's/^v//')" >> $GITHUB_OUTPUT

      - name: "Get Octofitter.jl version used in octtofitterpy"
        id: get-current
        run: |
          echo "version=$(python -c 'import octofitterpy; print(octofitterpy.version.__symbolic_regression_jl_version__)' 2>/dev/null)" >> $GITHUB_OUTPUT

      # If versions are different, we want to take our checked-out version,
      # create a new branch called "update_compat_{...}", where the "..."
      # is a timestamp. We then want to
      # go to octofitterpy/version.py, bump the patch version of octtofitterpy (__version__),
      # set the version of __symbolic_regression_jl_version__ to the latest
      # version of Octofitter.jl, and then commit and push.
      # Finally, we will open a PR from this branch to master.
      - name: "Update versions"
        if: ${{ steps.get-latest.outputs.version != steps.get-current.outputs.version }}
        run: |
          # Bump octtofitterpy patch number:
          CURRENT_OCTOFITTERPY_PATCH_VERSION=$(python -c 'import octofitterpy; print(octofitterpy.version.__version__.split(".")[-1], end="")' 2>/dev/null)
          NEW_OCTOFITTERPY_PATCH_VERSION=$((CURRENT_OCTOFITTERPY_PATCH_VERSION + 1))
          sed -i "s/^__version__ = .*/__version__ = \"$(python -c 'import octofitterpy; print(".".join(octofitterpy.version.__version__.split(".")[:-1]), end="")' 2>/dev/null).${NEW_OCTOFITTERPY_PATCH_VERSION}\"/" octofitterpy/version.py

          # Set Octofitter.jl version:
          sed -i "s/^__symbolic_regression_jl_version__ = .*/__symbolic_regression_jl_version__ = \"${{ steps.get-latest.outputs.version }}\"/" octofitterpy/version.py

      - name: "Create PR"
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          title: "Automated update to backend: v${{ steps.get-latest.outputs.version }}"
          body: |
            This PR was automatically generated by the GitHub Action `.github/workflows/update-backend.yml`

            It updates the backend version to v${{ steps.get-latest.outputs.version }}. For a full description of the changes, see the backend changelog: [v${{ steps.get-latest.outputs.version }}](https://github.com/sefffal/Octofitter.jl/releases/tag/v${{ steps.get-latest.outputs.version }}).
          delete-branch: true
          commit-message: "Update backend version to v${{ steps.get-latest.outputs.version }}"
          add-paths: octofitterpy/version.py
